### ISSUE TITLE
Collision detection

### ISSUE THREAD

**Issue by pkulev** [pkulev/xoinvader#19]
- add to entities field collider with some type and parameters
- add common mechanism for checking collisions
- provide set of colliders for different shapes (Sphere, Box, Custom shape)

``` python
class ERocketLauncher(Weapon):
    super(ERocketLauncher, self).__init__(**CONFIG[self.type])
    self._collider = SphereCollider(pos=Vec3(0, 0), radius=1)
    ...
```
- insert somewhere to right place collision detection routine for every appropriate object (maybe in event handlers)
## \* add code for actions on collision

Further collision detection code will be moved into engine and colliders will turn into components for lightweight entities.

Collision detection tightly coupled with `event system` and `object system`.

**Comment by taptap** [comment]
```python
>    self._collider = SphereCollider(pos=Vec3(0, 0), radius=1)
```
And right after this, on next update the object should already check for collisions with other objects, right?

**Comment by pkulev** [comment]
Yes. All collisions should check on `events` stage of iteration, on `update` stage game objects should know that collision detected and where.

**Comment by taptap** [comment]
What is `event` stage?
I'm afraid we don't quite have it.

**Comment by pkulev** [comment]
Please consider with `State` class.
